insert into stock_care_product_consume_detail (
    ID, STOCK_CARE_PRODUCT_CONSUME_ID, SUPPLIER_BATCH_NUMBER, SUPPLIER_CODE, SUPPLIER_NAME,
    AMOUNT, UNIT, UNIT_DESC, BATCH_NUMBER, CHARGE_ITEM_CODE, CHARGE_ITEM_NAME, DEDUCTION_EXECUTION_STEP_ID,
    STOCK_ADDRESS, STOCK_ADDRESS_DESC, FACTORY, FACTORY_DESC, MATERIAL_CODE, MATERIAL_DESC, MATERIAL_GROUP,
    LOCATION_TYPE, LOCATION_TYPE_DESC, STATUS, MANUFACTORE_DATE, EFFECTIVE_DATE, VERSION,
    CREATED_TIME, CREATED_BY_ID, CREATED_BY_NAME, UPDATED_TIME, UPDATED_BY_ID, UPDATED_BY_NAME, IS_AVAILABILITY, PLATFORM
) values (

         )